apiVersion: jumpapp.acidonpe.com/v1alpha1
kind: App
metadata:
  name: app-sample
spec:
  replicas: 2
  environment: development
  apps:
    - front-javascript
    - back-golang
  knative: false
  servicemesh: false